In [1]:
import numpy as np
import pandas as pd

In [5]:
data = pd.read_csv('play_tennis.csv')
data.head()

  day   outlook  temp humidity    wind play
0  D1     Sunny   Hot     High    Weak   No
1  D2     Sunny   Hot     High  Strong   No
2  D3  Overcast   Hot     High    Weak  Yes
3  D4      Rain  Mild     High    Weak  Yes
4  D5      Rain  Cool   Normal    Weak  Yes

In [6]:
data.drop(columns=['day'],inplace=True)
data.head()

    outlook  temp humidity    wind play
0     Sunny   Hot     High    Weak   No
1     Sunny   Hot     High  Strong   No
2  Overcast   Hot     High    Weak  Yes
3      Rain  Mild     High    Weak  Yes
4      Rain  Cool   Normal    Weak  Yes

In [25]:
data['play'].value_counts()

play
Yes    9
No     5
Name: count, dtype: int64

In [26]:
Py = 9/14

In [27]:
Pn = 5/14

In [28]:
print(f'py = {py}')
print(f'pn = {pn}')

py = 0.6428571428571429
pn = 0.35714285714285715

In [29]:
#Outlook

pd.crosstab(data['outlook'], data['play'])

play      No  Yes
outlook
Overcast   0    4
Rain       2    3
Sunny      3    2

In [30]:
POvercastNo = 0
PRainNo = 2/5
PSunnyNo = 3/5

POvercastYes = 4/9
PRainYes = 3/9
PSunnyYes = 2/9

In [31]:
# Temperature

pd.crosstab(data['temp'], data['play'])

play  No  Yes
temp
Cool   1    3
Hot    2    2
Mild   2    4

In [32]:
PCoolNo = 1/5
PHotNo = 2/5
PMildNo = 2/5

PCoolYes = 3/9
PHotYes = 2/9
PMildYes = 4/9

In [33]:
# Humidity

pd.crosstab(data['humidity'], data['play'])

play      No  Yes
humidity
High       4    3
Normal     1    6

In [34]:
PHighNo = 4/5
PNormalNo = 1/5

PHighYes = 3/9
PNormalYes = 6/9

In [35]:
# Wind

pd.crosstab(data['wind'], data['play'])

play    No  Yes
wind
Strong   3    3
Weak     2    6

In [36]:
PStrongNo = 3/5
PWeakNo = 2/5

PStrongYes = 3/9
PWeakYes = 6/9

In [38]:
# Outlook = Sunny, Temp=Hot, Humidity=High, Wind=weak

Pyes = Py * PSunnyYes * PHotYes * PHighYes * PWeakYes
print(f'Pyes = {Pyes}')

Pno = Pn * PSunnyNo * PHotNo * PHighNo * PWeakNo
print(f'Pno = {Pno}')

Pyes = 0.007054673721340388
Pno = 0.02742857142857143

In [42]:
print('Play? :', Pyes > Pno)

Play? : False