In [ ]:
import numpy as np
import pandas as pd

from sklearn.impute import SimpleImputer # SimpleImputer is a class from sklearn.impute used for handling missing values in datasets.
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

df = pd.read_csv('covid_toy.csv')

In [ ]:
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [ ]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.drop(columns=['has_covid']),df['has_covid'],
                                                test_size=0.2)

In [ ]:
X_train

    age  gender  fever   cough       city
73   34    Male   98.0  Strong    Kolkata
5    84  Female    NaN    Mild  Bangalore
41   82    Male    NaN    Mild    Kolkata
66   51    Male  104.0    Mild    Kolkata
56   71    Male    NaN  Strong    Kolkata
..  ...     ...    ...     ...        ...
40   49  Female  102.0    Mild      Delhi
81   65    Male   99.0    Mild      Delhi
88    5  Female  100.0    Mild    Kolkata
37   55    Male  100.0    Mild    Kolkata
50   19    Male  101.0    Mild      Delhi

[80 rows x 5 columns]

In [ ]:
# adding simple imputer to fever col
si = SimpleImputer()
X_train_fever = si.fit_transform(X_train[['fever']])

# also the test data
X_test_fever = si.transform(X_test[['fever']])

X_train_fever.shape

(80, 1)

In [ ]:
# Ordinalencoding -> cough
oe = OrdinalEncoder(categories=[['Mild','Strong']])
X_train_cough = oe.fit_transform(X_train[['cough']])

# also the test data
X_test_cough = oe.transform(X_test[['cough']])

X_train_cough.shape

(80, 1)

In [ ]:
# OneHotEncoding -> gender,city
ohe = OneHotEncoder(drop='first', sparse_output=False)

# for train data (fit_transform
X_train_gender_city = ohe.fit_transform(X_train[['gender','city']])

# also the test data
X_test_gender_city = ohe.transform(X_test[['gender','city']])

X_train_gender_city.shape

(80, 4)

In [ ]:
# Extracting Age
X_train_age = X_train.drop(columns=['gender','fever','cough','city']).values

# also the test data
X_test_age = X_test.drop(columns=['gender','fever','cough','city']).values

X_train_age.shape

(80, 1)

In [ ]:
if X_train_gender_city.ndim == 1:
    X_train_gender_city = X_train_gender_city.reshape(-1, 1)

In [ ]:
X_train_transformed = np.concatenate((X_train_age,X_train_fever,X_train_gender_city,X_train_cough),axis=1)
# also the test data
X_test_transformed = np.concatenate((X_test_age,X_test_fever,X_test_gender_city,X_test_cough),axis=1)

X_train_transformed.shape

(80, 7)

In [ ]:
from IPython.display import display, HTML

html_code = """
<h1> Column Transformer</h1>
"""

display(HTML(html_code))

In [ ]:
from sklearn.compose import ColumnTransformer

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.drop(columns=['has_covid']),df['has_covid'],
                                                test_size=0.2)

In [ ]:
transformer = ColumnTransformer(transformers=[
    ('tnf1',SimpleImputer(),['fever']),
    ('tnf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
    ('tnf3',OneHotEncoder(sparse_output=False,drop='first'),['gender','city'])
],remainder='passthrough')

In [ ]:
transformer.fit_transform(X_train).shape

(80, 7)

In [ ]:
transformer.transform(X_test).shape

(20, 7)

In [ ]:
df = pd.read_csv('customer.csv')

In [ ]:
df.sample(10)

    age  gender   review education purchased
47   38  Female     Good        PG       Yes
43   27    Male     Poor        PG        No
38   45  Female     Good    School        No
4    16  Female  Average        UG        No
20   57  Female  Average    School       Yes
49   25  Female     Good        UG        No
23   96  Female     Good    School        No
31   22  Female     Poor    School       Yes
45   61    Male     Poor        PG       Yes
26   53  Female     Poor        PG        No

In [ ]:
df.isnull().sum()

age          0
gender       0
review       0
education    0
purchased    0
dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.drop(columns=['purchased']),df['purchased'],
                                                test_size=0.2)

In [ ]:
transformer = ColumnTransformer(transformers=[
    ('tnf1',OrdinalEncoder(categories=[['School','UG','PG']]),['education']),
    ('tnf2',OneHotEncoder(sparse_output=False,drop='first'),['gender']),
    ('tnf3',OrdinalEncoder(categories=[['Poor','Average','Good']]),['review']),

],remainder='passthrough')

In [ ]:
transformer.fit_transform(X_train).shape

(40, 4)

In [ ]:
transformer.transform(X_test).shape

(10, 4)